### ISSUE TITLE
Is decimal128 broken?

### ISSUE THREAD

**Issue by jtrees** [arteymix/numeric-glib#11]
```vala
private static inline void test_foo () {
    Numeric.decimal128 a = 0.1;
    Numeric.decimal128 b = 0.1;
    Numeric.decimal128 c = 0.1;
    Numeric.decimal128 d = -0.3;

    Numeric.decimal128 expected = 0;

    assert_true (a + b + c + d == expected);
}
```

This test fails for me. It works if I replace `decimal128` with `decimal64` though. What's going on?

**Comment by arteymix** [comment]
That looks very concerning. 

I looked the generated C code for that snippet and there is no conversion to any other floating types.

In GCC docs (https://gcc.gnu.org/onlinedocs/gcc-7.5.0/gcc/Decimal-Float.html), it states that not all target support these types. I believe it is being emulated by software.

I'll try to integrate libdfp (https://github.com/libdfp/libdfp) so that we can fill the missing I/O routines.

**Comment by arteymix** [comment]
It's not broken. When you write `0.1`, it's actually a double literal. The compiler does not cast anything but rather choose a number close by it can represent.

If you were to write this in C, you would have to use an extension suffix `0.1DF` to make it work.

I don't think there is a way to do this that would not involve a Vala compiler plugin as we would have to generate custom code for that (interesting project!). The workaround is to add I/O primitive so that one can do something like:

```vala
var a = decimal128.parse ("0.1");
print (a.to_string ())
```

**Comment by jtrees** [comment]
I see. Will you add this?

**Comment by arteymix** [comment]
Now superseded by #12
